package ServerImplementation;


/**
* ServerImplementation/ServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerImplementation.idl
* Wednesday, October 25, 2017 12:11:15 PM EDT
*/

public interface ServerInterface extends ServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerInterface
