package ServerImplementation;

/**
* ServerImplementation/ServerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerImplementation.idl
* Wednesday, October 25, 2017 12:11:15 PM EDT
*/

public final class ServerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public ServerImplementation.ServerInterface value = null;

  public ServerInterfaceHolder ()
  {
  }

  public ServerInterfaceHolder (ServerImplementation.ServerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServerImplementation.ServerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServerImplementation.ServerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServerImplementation.ServerInterfaceHelper.type ();
  }

}
