package ServerImplementation;


/**
* ServerImplementation/ServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerImplementation.idl
* Wednesday, October 25, 2017 12:11:15 PM EDT
*/

public interface ServerInterfaceOperations 
{
  String createRoom (String adminID, int roomNumber, String date, String listOfTimeSlots);
  String deleteRoom (String adminID, int roomNumber, String date, String listOfTimeSlots);
  String bookRoom (String studentID, int campus, int roomNumber, String date, String startTime, String endTime);
  String getAvailableTimeSlot (String studentID, String date);
  String cancelBooking (String studentID, String bookingID);
  String changeReservation (String studentID, String bookingID, int campus, int roomNumber, String startTime, String endTime);
  boolean setAdminID (String adminID);
  boolean setStudentID (String studentID);
  void signOut (String ID);
} // interface ServerInterfaceOperations
