package comp6231.project.saman.common.corba.users;


/**
* comp6231/project/saman/common/corba/users/_AdminOperationsStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SamanOperations.idl
* Saturday, November 11, 2017 9:10:31 PM EST
*/

public class _AdminOperationsStub extends org.omg.CORBA.portable.ObjectImpl implements comp6231.project.saman.common.corba.users.AdminOperations
{

  public boolean createRoom (String user_id, int room_number, comp6231.project.saman.common.corba.data_structure.CorbaDateReservation date, comp6231.project.saman.common.corba.data_structure.CorbaTimeSlot[] time_slots)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createRoom", true);
                $out.write_string (user_id);
                $out.write_long (room_number);
                comp6231.project.saman.common.corba.users.CorbaDateReservationHelper.write ($out, date);
                comp6231.project.saman.common.corba.users.corba_timeslot_listHelper.write ($out, time_slots);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return createRoom (user_id, room_number, date, time_slots        );
            } finally {
                _releaseReply ($in);
            }
  } // createRoom

  public boolean deleteRoom (String user_id, int room_number, comp6231.project.saman.common.corba.data_structure.CorbaDateReservation date, comp6231.project.saman.common.corba.data_structure.CorbaTimeSlot[] time_slots)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("deleteRoom", true);
                $out.write_string (user_id);
                $out.write_long (room_number);
                comp6231.project.saman.common.corba.users.CorbaDateReservationHelper.write ($out, date);
                comp6231.project.saman.common.corba.users.corba_timeslot_listHelper.write ($out, time_slots);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return deleteRoom (user_id, room_number, date, time_slots        );
            } finally {
                _releaseReply ($in);
            }
  } // deleteRoom

  public boolean startWeek (String user_id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("startWeek", true);
                $out.write_string (user_id);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return startWeek (user_id        );
            } finally {
                _releaseReply ($in);
            }
  } // startWeek

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:comp6231/project/saman/common/corba/users/AdminOperations:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _AdminOperationsStub
