package comp6231.project.saman.common.corba.users;


/**
* comp6231/project/saman/common/corba/users/AdminOperationsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SamanOperations.idl
* Saturday, November 11, 2017 9:10:31 PM EST
*/

public interface AdminOperationsOperations 
{
  boolean createRoom (String user_id, int room_number, comp6231.project.saman.common.corba.data_structure.CorbaDateReservation date, comp6231.project.saman.common.corba.data_structure.CorbaTimeSlot[] time_slots);
  boolean deleteRoom (String user_id, int room_number, comp6231.project.saman.common.corba.data_structure.CorbaDateReservation date, comp6231.project.saman.common.corba.data_structure.CorbaTimeSlot[] time_slots);
  boolean startWeek (String user_id);
} // interface AdminOperationsOperations
