package comp6231.project.saman.common.corba.users;


/**
* comp6231/project/saman/common/corba/users/corba_timeslot_listHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SamanOperations.idl
* Saturday, November 11, 2017 9:10:31 PM EST
*/

abstract public class corba_timeslot_listHelper
{
  private static String  _id = "IDL:comp6231/project/saman/common/corba/users/corba_timeslot_list:1.0";

  public static void insert (org.omg.CORBA.Any a, comp6231.project.saman.common.corba.data_structure.CorbaTimeSlot[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static comp6231.project.saman.common.corba.data_structure.CorbaTimeSlot[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = comp6231.project.saman.common.corba.data_structure.CorbaTimeSlotHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (comp6231.project.saman.common.corba.users.CorbaTimeSlotHelper.id (), "CorbaTimeSlot", __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (comp6231.project.saman.common.corba.users.corba_timeslot_listHelper.id (), "corba_timeslot_list", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static comp6231.project.saman.common.corba.data_structure.CorbaTimeSlot[] read (org.omg.CORBA.portable.InputStream istream)
  {
    comp6231.project.saman.common.corba.data_structure.CorbaTimeSlot value[] = null;
    int _len0 = istream.read_long ();
    value = new comp6231.project.saman.common.corba.data_structure.CorbaTimeSlot[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = comp6231.project.saman.common.corba.users.CorbaTimeSlotHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, comp6231.project.saman.common.corba.data_structure.CorbaTimeSlot[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      comp6231.project.saman.common.corba.users.CorbaTimeSlotHelper.write (ostream, value[_i0]);
  }

}
