package comp6231.project.saman.common.corba.users;


/**
* comp6231/project/saman/common/corba/users/StudentOperationsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SamanOperations.idl
* Saturday, November 11, 2017 9:10:31 PM EST
*/

public interface StudentOperationsOperations 
{
  String bookRoom (String user_id, String campus_name, int room_number, comp6231.project.saman.common.corba.data_structure.CorbaDateReservation date, comp6231.project.saman.common.corba.data_structure.CorbaTimeSlot time_slot);
  comp6231.project.saman.common.corba.data_structure.CorbaTimeSlotResult[] getAvailableTimeSlot (String user_id, comp6231.project.saman.common.corba.data_structure.CorbaDateReservation date);
  boolean cancelBooking (String user_id, String bookingID);
  String changeReservation (String user_id, String booking_id, String new_campus_name, int new_room_number, comp6231.project.saman.common.corba.data_structure.CorbaDateReservation new_date, comp6231.project.saman.common.corba.data_structure.CorbaTimeSlot new_time_slot);
} // interface StudentOperationsOperations
