module comp6231 { module project { module common { module corba { module users {
    valuetype nullable_string string;
    
    typedef sequence<nullable_string> corba_timeslot_list;
    
    interface StudentOperations
    {
	string bookRoom(in string user_id, in string campus_name, in long room_number, in string date, in string time_slot);
	string getAvailableTimeSlot(in string user_id, in string date);
	string cancelBooking(in string user_id, in string bookingID);
	string changeReservation(in string user_id, in string booking_id, in string new_campus_name, in long new_room_number, in string new_date, in string new_time_slot);
	boolean studentLogin(in string studentID);
	oneway void signOut(in string ID);
    };
    
    interface AdminOperations
    {        
	string createRoom(in string user_id, in long room_number, in string date, in corba_timeslot_list time_slots);
	string deleteRoom(in string user_id, in long room_number, in string date, in corba_timeslot_list time_slots);
	boolean adminLogin(in string adminID);
	oneway void signOut(in string ID);
    };
    
};};};};};


