package comp6231.project.saman.common.corba.campus;


/**
* comp6231/project/saman/common/corba/campus/CampusOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SamanOperations.idl
* Saturday, November 11, 2017 9:10:31 PM EST
*/

public interface CampusOperations extends CampusOperationsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CampusOperations
