package comp6231.project.saman.common.corba.campus;


/**
* comp6231/project/saman/common/corba/campus/CampusOperationsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SamanOperations.idl
* Saturday, November 11, 2017 9:10:31 PM EST
*/

public abstract class CampusOperationsPOA extends org.omg.PortableServer.Servant
 implements comp6231.project.saman.common.corba.campus.CampusOperationsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getPort", new java.lang.Integer (0));
    _methods.put ("getAddress", new java.lang.Integer (1));
    _methods.put ("getCampusName", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // comp6231/project/saman/common/corba/campus/CampusOperations/getPort
       {
         int $result = (int)0;
         $result = this.getPort ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // comp6231/project/saman/common/corba/campus/CampusOperations/getAddress
       {
         String $result = null;
         $result = this.getAddress ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // comp6231/project/saman/common/corba/campus/CampusOperations/getCampusName
       {
         String $result = null;
         $result = this.getCampusName ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:comp6231/project/saman/common/corba/campus/CampusOperations:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CampusOperations _this() 
  {
    return CampusOperationsHelper.narrow(
    super._this_object());
  }

  public CampusOperations _this(org.omg.CORBA.ORB orb) 
  {
    return CampusOperationsHelper.narrow(
    super._this_object(orb));
  }


} // class CampusOperationsPOA
