package comp6231.project.saman.common.corba.campus;

/**
* comp6231/project/saman/common/corba/campus/CampusOperationsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SamanOperations.idl
* Saturday, November 11, 2017 9:10:31 PM EST
*/

public final class CampusOperationsHolder implements org.omg.CORBA.portable.Streamable
{
  public comp6231.project.saman.common.corba.campus.CampusOperations value = null;

  public CampusOperationsHolder ()
  {
  }

  public CampusOperationsHolder (comp6231.project.saman.common.corba.campus.CampusOperations initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = comp6231.project.saman.common.corba.campus.CampusOperationsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    comp6231.project.saman.common.corba.campus.CampusOperationsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return comp6231.project.saman.common.corba.campus.CampusOperationsHelper.type ();
  }

}
