package comp6231.project.saman.common.corba.campus;


/**
* comp6231/project/saman/common/corba/campus/CampusOperationsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SamanOperations.idl
* Saturday, November 11, 2017 9:10:31 PM EST
*/

public interface CampusOperationsOperations 
{
  int getPort ();
  String getAddress ();
  String getCampusName ();
} // interface CampusOperationsOperations
