package comp6231.project.saman.common.corba.data_structure;


/**
* comp6231/project/saman/common/corba/data_structure/CorbaTimeSlot.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SamanOperations.idl
* Saturday, November 11, 2017 9:10:31 PM EST
*/

public final class CorbaTimeSlot implements org.omg.CORBA.portable.IDLEntity
{
  public int hour1 = (int)0;
  public int minute1 = (int)0;
  public int hour2 = (int)0;
  public int minute2 = (int)0;

  public CorbaTimeSlot ()
  {
  } // ctor

  public CorbaTimeSlot (int _hour1, int _minute1, int _hour2, int _minute2)
  {
    hour1 = _hour1;
    minute1 = _minute1;
    hour2 = _hour2;
    minute2 = _minute2;
  } // ctor

} // class CorbaTimeSlot
