package comp6231.project.saman.common.corba.data_structure;

/**
* comp6231/project/saman/common/corba/data_structure/CorbaDateReservationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SamanOperations.idl
* Saturday, November 11, 2017 9:10:31 PM EST
*/

public final class CorbaDateReservationHolder implements org.omg.CORBA.portable.Streamable
{
  public comp6231.project.saman.common.corba.data_structure.CorbaDateReservation value = null;

  public CorbaDateReservationHolder ()
  {
  }

  public CorbaDateReservationHolder (comp6231.project.saman.common.corba.data_structure.CorbaDateReservation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = comp6231.project.saman.common.corba.data_structure.CorbaDateReservationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    comp6231.project.saman.common.corba.data_structure.CorbaDateReservationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return comp6231.project.saman.common.corba.data_structure.CorbaDateReservationHelper.type ();
  }

}
