package comp6231.project.saman.common.corba.data_structure;


/**
* comp6231/project/saman/common/corba/data_structure/CorbaTimeSlotResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SamanOperations.idl
* Saturday, November 11, 2017 9:10:31 PM EST
*/

public final class CorbaTimeSlotResult implements org.omg.CORBA.portable.IDLEntity
{
  public String campus_name = null;
  public int total_available_slots = (int)0;

  public CorbaTimeSlotResult ()
  {
  } // ctor

  public CorbaTimeSlotResult (String _campus_name, int _total_available_slots)
  {
    campus_name = _campus_name;
    total_available_slots = _total_available_slots;
  } // ctor

} // class CorbaTimeSlotResult
