package comp6231.project.saman.common.corba.data_structure;

/**
* comp6231/project/saman/common/corba/data_structure/CorbaTimeSlotHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from SamanOperations.idl
* Saturday, November 11, 2017 9:10:31 PM EST
*/

public final class CorbaTimeSlotHolder implements org.omg.CORBA.portable.Streamable
{
  public comp6231.project.saman.common.corba.data_structure.CorbaTimeSlot value = null;

  public CorbaTimeSlotHolder ()
  {
  }

  public CorbaTimeSlotHolder (comp6231.project.saman.common.corba.data_structure.CorbaTimeSlot initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = comp6231.project.saman.common.corba.data_structure.CorbaTimeSlotHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    comp6231.project.saman.common.corba.data_structure.CorbaTimeSlotHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return comp6231.project.saman.common.corba.data_structure.CorbaTimeSlotHelper.type ();
  }

}
