package comp6231.project.common.corba.users;


/**
* comp6231/project/common/corba/users/AdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operations.idl
* Wednesday, December 6, 2017 5:02:12 PM EST
*/

public interface AdminOperations extends AdminOperationsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdminOperations
