package comp6231.project.common.corba.users;


/**
* comp6231/project/common/corba/users/AdminOperationsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operations.idl
* Friday, December 1, 2017 4:13:59 PM EST
*/

public interface AdminOperationsOperations 
{
  String createRoom (String user_id, int room_number, String date, String[] time_slots);
  String deleteRoom (String user_id, int room_number, String date, String[] time_slots);
  boolean adminLogin (String adminID);
  void signOut (String ID);
  String killServer (String campusName);
} // interface AdminOperationsOperations
