package comp6231.project.common.corba.users;


/**
* comp6231/project/common/corba/users/AdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operations.idl
* Thursday, December 7, 2017 12:30:29 AM EST
*/

public interface AdminOperations extends AdminOperationsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdminOperations
