package comp6231.project.common.corba.users;


/**
* comp6231/project/common/corba/users/AdminOperationsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operations.idl
* Thursday, December 7, 2017 12:30:29 AM EST
*/

abstract public class AdminOperationsHelper
{
  private static String  _id = "IDL:comp6231/project/common/corba/users/AdminOperations:1.0";

  public static void insert (org.omg.CORBA.Any a, comp6231.project.common.corba.users.AdminOperations that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static comp6231.project.common.corba.users.AdminOperations extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (comp6231.project.common.corba.users.AdminOperationsHelper.id (), "AdminOperations");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static comp6231.project.common.corba.users.AdminOperations read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AdminOperationsStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, comp6231.project.common.corba.users.AdminOperations value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static comp6231.project.common.corba.users.AdminOperations narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof comp6231.project.common.corba.users.AdminOperations)
      return (comp6231.project.common.corba.users.AdminOperations)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      comp6231.project.common.corba.users._AdminOperationsStub stub = new comp6231.project.common.corba.users._AdminOperationsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static comp6231.project.common.corba.users.AdminOperations unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof comp6231.project.common.corba.users.AdminOperations)
      return (comp6231.project.common.corba.users.AdminOperations)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      comp6231.project.common.corba.users._AdminOperationsStub stub = new comp6231.project.common.corba.users._AdminOperationsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
