package comp6231.project.common.corba.users;


/**
* comp6231/project/common/corba/users/corba_timeslot_listHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/wmg/Documents/workspace/Comp6231-Project/Operations.idl
* Thursday, November 9, 2017 10:26:03 PM EST
*/

public final class corba_timeslot_listHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public corba_timeslot_listHolder ()
  {
  }

  public corba_timeslot_listHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = comp6231.project.common.corba.users.corba_timeslot_listHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    comp6231.project.common.corba.users.corba_timeslot_listHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return comp6231.project.common.corba.users.corba_timeslot_listHelper.type ();
  }

}
