package comp6231.project.common.corba.users;


/**
* comp6231/project/common/corba/users/StudentOperationsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operations.idl
* Thursday, December 7, 2017 12:30:29 AM EST
*/

public abstract class StudentOperationsPOA extends org.omg.PortableServer.Servant
 implements comp6231.project.common.corba.users.StudentOperationsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("bookRoom", new java.lang.Integer (0));
    _methods.put ("getAvailableTimeSlot", new java.lang.Integer (1));
    _methods.put ("cancelBooking", new java.lang.Integer (2));
    _methods.put ("changeReservation", new java.lang.Integer (3));
    _methods.put ("studentLogin", new java.lang.Integer (4));
    _methods.put ("signOut", new java.lang.Integer (5));
    _methods.put ("killServer", new java.lang.Integer (6));
    _methods.put ("fakeGenerate", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // comp6231/project/common/corba/users/StudentOperations/bookRoom
       {
         String user_id = in.read_string ();
         String campus_name = in.read_string ();
         int room_number = in.read_long ();
         String date = in.read_string ();
         String time_slot = in.read_string ();
         String $result = null;
         $result = this.bookRoom (user_id, campus_name, room_number, date, time_slot);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // comp6231/project/common/corba/users/StudentOperations/getAvailableTimeSlot
       {
         String user_id = in.read_string ();
         String date = in.read_string ();
         String $result = null;
         $result = this.getAvailableTimeSlot (user_id, date);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // comp6231/project/common/corba/users/StudentOperations/cancelBooking
       {
         String user_id = in.read_string ();
         String bookingID = in.read_string ();
         String $result = null;
         $result = this.cancelBooking (user_id, bookingID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // comp6231/project/common/corba/users/StudentOperations/changeReservation
       {
         String user_id = in.read_string ();
         String booking_id = in.read_string ();
         String new_campus_name = in.read_string ();
         int new_room_number = in.read_long ();
         String new_date = in.read_string ();
         String new_time_slot = in.read_string ();
         String $result = null;
         $result = this.changeReservation (user_id, booking_id, new_campus_name, new_room_number, new_date, new_time_slot);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // comp6231/project/common/corba/users/StudentOperations/studentLogin
       {
         String studentID = in.read_string ();
         boolean $result = false;
         $result = this.studentLogin (studentID);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // comp6231/project/common/corba/users/StudentOperations/signOut
       {
         String ID = in.read_string ();
         this.signOut (ID);
         out = $rh.createReply();
         break;
       }

       case 6:  // comp6231/project/common/corba/users/StudentOperations/killServer
       {
         String replicaCampusName = in.read_string ();
         this.killServer (replicaCampusName);
         out = $rh.createReply();
         break;
       }

       case 7:  // comp6231/project/common/corba/users/StudentOperations/fakeGenerate
       {
         String replicaName = in.read_string ();
         String campusName = in.read_string ();
         this.fakeGenerate (replicaName, campusName);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:comp6231/project/common/corba/users/StudentOperations:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public StudentOperations _this() 
  {
    return StudentOperationsHelper.narrow(
    super._this_object());
  }

  public StudentOperations _this(org.omg.CORBA.ORB orb) 
  {
    return StudentOperationsHelper.narrow(
    super._this_object(orb));
  }


} // class StudentOperationsPOA
