package comp6231.project.common.corba.users;


/**
* comp6231/project/common/corba/users/StudentOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Operations.idl
* Friday, December 1, 2017 4:13:59 PM EST
*/

public interface StudentOperations extends StudentOperationsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StudentOperations
